make dir_obj_type a table instead of cdata, avoids DIR* being a dangl…
spacewander/luafilesystem pull request #10
Opened 2021-02-23 13:54 UTC by sonoro1234

…ing pointer

I could not test. Sorry!!

2021-02-24 01:15 UTC, spacewander requested changes

2021-02-24 01:15 UTC, spacewander commented on lfs_ffi.lua
>  }, __gc = close
I think we need to make the `__gc` work as user can bypass the `close` with calling `next` directly.

2021-02-24 01:28 UTC, spacewander commented on lfs_ffi.lua
>  }, __gc = close
Could you add a test like this one: https://github.com/spacewander/luafilesystem/blob/10831d3de10acaa28ff58e939ed0f7c4f4d2424f/lfs_spec.lua#L200 but only iterate for one or two times?

2021-02-24 11:32 UTC, sonoro1234 commented
I am not sure my proposal is needed at all:
https://github.com/spacewander/luafilesystem/issues/9#issuecomment-784324222

2021-02-25 01:08 UTC, spacewander commented
We can clear it in the `close` method.

2021-02-25 09:10 UTC, sonoro1234 commented
> I am not sure my proposal is needed at all:
> [#9 (comment)](https://github.com/spacewander/luafilesystem/issues/9#issuecomment-784324222)



> We can clear it in the `close` method.

My proposal? :-)

2021-02-25 10:28 UTC, spacewander commented
I think it again...
Yes, you are right. We don't care about the object's life cycle, we only need it value (the address). So it seems everything is already fine...

2021-02-25 10:36 UTC, closed without merging

2021-02-25 10:36 UTC, sonoro1234 commented
Sorry for the noise!!!